# Generated by Django 3.2.23 on 2023-12-07 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_alter_customuser_stdclass'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentclass',
            name='std',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
