# Generated by Django 3.2.23 on 2023-12-07 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_auto_20231208_0032'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('total_student', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='student',
            name='stdclass',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='student.classdetail'),
        ),
        migrations.DeleteModel(
            name='StudentClass',
        ),
    ]
