# Generated by Django 3.2.23 on 2023-12-08 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_auto_20231208_0039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='status',
        ),
        migrations.AddField(
            model_name='customuser',
            name='status',
            field=models.IntegerField(choices=[(1, 'inactive'), (2, 'active')], default=1),
        ),
    ]
